# Name of the tactile sensor source.
string sensor_name

# Present pressure values from the tactile sensor (3x3 grid base)
# Pressure indices are ordered from top to bottom, and from left to right within each row.
float32 present_pressure_1
float32 present_pressure_2
float32 present_pressure_3
float32 present_pressure_4
float32 present_pressure_5
float32 present_pressure_6
float32 present_pressure_7
float32 present_pressure_8
float32 present_pressure_9
